### ISSUE TITLE
wdinstagram HW

### ISSUE THREAD

**Issue by StormyRamsey** [ga-wdi-exercises/wdinstagram_angular#98]
https://github.com/StormyRamsey/wdinstagram_angular_hw

I had to create a new repo because of my folder change that I made after completing part 1. 
Could not figure out how to connect app to rails server. 

Comfort level 3
Completion level 3.5

**Comment by juancgarcia** [comment]
👍 Good effort here. You had a couple of hard to catch angular bugs in your `app.js` code:

The `.module` call was set to `Entry` but in index.html you have `ng-app="entry"`. Need to change it to:
```js
.module("entry", [
```
in the `.config` call, `stateProvider` needs the `$` sign:
```js
"$stateProvider",
```

and finally, your `EntryIndexControllerFunction` has the wrong parameter name. It should match the factory name you're using to query your resource:
```js
function EntryIndexControllerFunction(EntryFactory) {
```
